### ISSUE TITLE
Generate an SVG file instead of an HTML table

### ISSUE THREAD

**Issue by hwhsu1231** [andrii-bodnar/action-crowdin-contributors#92]
### Feature Request

Hello, @andrii-bodnar 

I wonder whether this GitHub Action can provide a new mode to generate an SVG file displaying all the Crowdin contributors.

There are some relavent projects that I found in GitHub:

* [antfu/sponsorkit](https://github.com/antfu/sponsorkit)
* [Xhofe/gh-contributors](https://github.com/Xhofe/gh-contributors)

which can generate an SVG file to display sponsors or contributors.

It would be better for me to have an SVG file displaying all the contributors instead of inserting an HTML tables into README.md

**Comment by andrii-bodnar** [comment]
@hwhsu1231 thank you for the suggestion!

I like the idea. I think we can introduce a new boolean input:

```yml
svg:
  description: "Generate table in SVG format"
  default: 'false'
  required: false
```

**Comment by hwhsu1231** [comment]
Maybe this GitHub Action, [contributors-list](https://github.com/wow-actions/contributors-list), can be a good example to refer to?

**Comment by hwhsu1231** [comment]
Hello, @andrii-bodnar 

I tried the [v3.1.0](https://github.com/andrii-bodnar/action-crowdin-contributors/tree/v3.1.0) release, which includes the merged commit https://github.com/andrii-bodnar/action-crowdin-contributors/commit/4c2c018cff56f0add69287ccfcdc67165eebf95e, with the following codes:

```yml
- name: Generate Crowdin Contributors
  uses: andrii-bodnar/action-crowdin-contributors@v3.1.0
  with:
    svg: true
    svg_output_path: 'out/${{ inputs.DEPLOY_BRANCH }}/crowdin-contributors.svg'
    contributors_per_line: 8
    max_contributors: 32
    image_size: 64
  env:
    CROWDIN_PROJECT_ID: ${{ inputs.CROWDIN_PROJECT_ID }}
    CROWDIN_ORGANIZATION: ${{ inputs.CROWDIN_BASE_URL }}
    CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
```

However, it failed with the following error messages:

```bash
Run andrii-bodnar/action-crowdin-contributors@v3.1.0
  with:
    svg: true
    svg_output_path: out/static/crowdin-contributors.svg
    contributors_per_line: 8
    max_contributors: 32
    image_size: 64
    min_words_contributed: 100
    files: README.md
    placeholder_start: <!-- CROWDIN-CONTRIBUTORS-START -->
    placeholder_end: <!-- CROWDIN-CONTRIBUTORS-END -->
  env:
    CROWDIN_PROJECT_ID: 1
    CROWDIN_ORGANIZATION: https://ltdorgtest.api.crowdin.com/
    CROWDIN_PERSONAL_TOKEN: ***
[dotenv@17.2.3] injecting env (0) from .env -- tip: ⚙️  enable debug logging with { debug: true }
Validating files...
Downloading the report...
(node:2286) [DEP0169] DeprecationWarning: `url.parse()` behavior is not standardized and prone to errors that have security implications. Use the WHATWG URL API instead. CVEs are not issued for `url.parse()` vulnerabilities.
(Use `node --trace-deprecation ...` to show where the warning was created)
Error: Cannot generate report
```
